### ISSUE TITLE
Script does not work as of 2020-10-12

### ISSUE THREAD

**Issue by wabee** [MattC137/Election-Predictor-Trump-vs-Biden#1]
Error in filter(., Poll != rcp_average) : object 'Poll' not found when executing line 116 'state_polls <- state_polls %>% filter(Poll != rcp_average)'.

**Comment by MattC137** [comment]
The code seems to be running through for me. I'm on r-version 3.6.1. Maybe there is a versioning problem?

perhaps you can take a screen shot to help me diagnose?

**Comment by wabee** [comment]
Hello

I’m on R 4.02, that’s likely the problem. As far as I can tell the code looks fine. 
I’ll take a look later and see if I can diagnose. I don’t believe a screen shot will help much though. Happy to help.

**Comment by wabee** [comment]
Tried the code on my Mac also running R 4.02. The script works there but not on a Windows PC. As a note, the final results are not printed out on the Mac screen. But manually executing the code works
`results %>% 
        group_by(winner) %>% 
        tally() %>% 
        rename(Percent = n) %>%   
        mutate(Percent = scales::percent(Percent/n, accuracy = `1.0))`

**Comment by MattC137** [comment]
Interesting...

Thanks for testing this out. Seems like something I should look into.

**Comment by wabee** [comment]
Noticed that R 4.03 is released. Will upgrade the Windows PC to that version and try again and see how it goes. Pretty fishy ...

**Comment by wabee** [comment]
Hello  Upgraded R to 4.03 on my Windows PC. Didn’t help. But, changing all occurences of ’filter(… ’ to ’dplyr::filter’ did the trick.It seems that my R environment is trying to use filter from a different package unless I specify that ’filter’ from dplyr is explictly specified.I also get a warning, both in Windows and on Mac but seem harmless:’ In stri_extract_all_regex(string, pattern, simplify = simplify,  :  argument is not an atomic vector; coercing’ Cheers
