### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by jmagomez** [MattC137/Election-Predictor-Trump-vs-Biden#2]
Dear MattC137,
I ran the same code, but I have experienced two issues:
1)	Line 92 
State_Polls_2020_PA[[4]]

Should not it be? State_Polls_2020_PA[[2]]

1)	Line 302

After the loop, the Standard Deviation from Nebraska CD2 and Alabama remains NA.

Best Regards, José.

**Comment by jmagomez** [comment]
And congratulations for this great work!

**Comment by MattC137** [comment]
Thanks for the find!

It looks like RCP changed the layout for PA. I've changed the code to State_Polls_2020_PA[[2]] as you've pointed out.

It also looks like I didn't handle conditions where there there is a stdev for 2020 but not 2016.

I've pushed the changes and it seems to have fixed the problem.

**Comment by jmagomez** [comment]
Thanks for the reply!

I ran this new code and it worked. Congratulations for this great code!

Best Regards.

Em dom., 1 de nov. de 2020 às 21:49, MattC137 <notifications@github.com>
escreveu:
